var express = require('express')
var app = express()
var bodyParser = require('body-parser')
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended: true}))
var apiRoutes = require("./routes.js");
var routeInstance = new apiRoutes(app)
routeInstance.init()
app.listen(9501)
console.log("Server Listening")